

DROP TABLE IF EXISTS `ACCOUNT`;
CREATE TABLE `ACCOUNT` (
  `ID` int(10) NOT NULL,
  `CONTACT_ID` int(11) DEFAULT NULL,
  `NAME` varchar(256)  DEFAULT NULL,
  `TYPE` varchar(32)  DEFAULT NULL,
  `DESCRIPTION` varchar(225)  DEFAULT NULL,
  `CONTACT_NAME` varchar(256)  DEFAULT NULL,
  `STREET` varchar(256)  DEFAULT NULL,
  `CITY` varchar(32)  DEFAULT NULL,
  `STATE` varchar(32)  DEFAULT NULL,
  `ZIP` varchar(32)  DEFAULT NULL,
  PRIMARY KEY (`ID`)
);


DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID` int(10) NOT NULL,
  `EMAIL` varchar(256) DEFAULT NULL,
  `ACCOUNT_ID` int(10),
  PRIMARY KEY (`ID`)
);


