

DROP TABLE IF EXISTS `ACCOUNT`;
CREATE TABLE `ACCOUNT` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `CONTACT_ID` int(11) DEFAULT NULL,
  `NAME` varchar(256)  DEFAULT NULL,
  `TYPE` varchar(32)  DEFAULT NULL,
  `DESCRIPTION` varchar(225)  DEFAULT NULL,
  `CONTACT_NAME` varchar(256)  DEFAULT NULL,
  `STREET` varchar(256)  DEFAULT NULL,
  `CITY` varchar(32)  DEFAULT NULL,
  `STATE` varchar(32)  DEFAULT NULL,
  `ZIP` varchar(32)  DEFAULT NULL,
  PRIMARY KEY (`ID`)
);


DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(256) DEFAULT NULL,
  `ACCOUNT_ID` int(10),
   CONSTRAINT `ACCOUNT_FK` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `ACCOUNT` (`ID`),
  PRIMARY KEY (`ID`)
);



DROP TABLE IF EXISTS `version`;
CREATE TABLE `version` (
  `scn` int(10) unsigned NOT NULL
);


DELIMITER ;;
CREATE FUNCTION `get_version`() RETURNS int(11)
    READS SQL DATA
BEGIN
    DECLARE result INT DEFAULT 1;
    SELECT coalesce(max(scn), 1) INTO result FROM version;
    RETURN result;
END ;;
DELIMITER ;

